$SERVICE_REGION$/apps/$SERVICE_NAME$/api/service-url: https://127.0.0.1:902
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/service-key: base64:s0iHLc3j85XeAPiwJVN+5UXuKuq0S3UxD5GGU9pjMlE=

$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/host: pm-mysql
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/instance: main
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/database: pm
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/username: root
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/password: example
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/db/port: 3306

$SERVICE_REGION$/apps/$SERVICE_NAME$/api/queue/driver: sync

$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/host: pm-redis
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/instance: pm
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/db_number: 0
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/sessions_db: 1
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/rw_timeout: 60
$SERVICE_REGION$/apps/$SERVICE_NAME$/api/redis/port: 6379

$SERVICE_REGION$/apps/$SERVICE_NAME$/front/service-url: https://127.0.0.1:903
$SERVICE_REGION$/apps/$SERVICE_NAME$/front/service-key: base64:s0iHLc3j85XeAPiwJVN+5UXuKuq0S3UxD5GGU9pjMlE=
$SERVICE_REGION$/apps/$SERVICE_NAME$/front/api/host: http://localhost:904
$SERVICE_REGION$/apps/$SERVICE_NAME$/front/api/host_internal: http://pm-app-api
