name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  abrouter-tests-php-74:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: bestpass
          MYSQL_DATABASE: abr-test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        phpunit-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'

    steps:
      - uses: actions/checkout@v2
      - name: Update Composer
        run: mkdir bootstrap/cache && chmod -R 777 bootstrap/cache && composer self-update 1.10.21 --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: run tests
        run: |
          php artisan migrate
          php artisan passport:install
          rm .env
          cp .env.ci .env
          vendor/bin/codecept run
